package com.xuan.user.facadeimpl.mapper;

import com.xuan.user.facadeimpl.entity.RoleAuthority;

public interface RoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int insert(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int insertSelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    RoleAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleAuthority record);
}