server:
  port: 8000

spring:
  application:
    name: shop-user-facade-impl
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: loan
    password: 51xfjianglei@2018!
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


mylogging:
  level: INFO
  file:
    path: /opt/soft/logs/shop-user-impl
    name: shop-user.log