package com.xuan.user.facadeimpl.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_authority
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Authority {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限字符
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_name
     *
     * @mbg.generated
     */
    private String authName;

    /**
     * Database Column Remarks:
     *   权限名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_desc
     *
     * @mbg.generated
     */
    private String authDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.id
     *
     * @return the value of sys_authority.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.id
     *
     * @param id the value for sys_authority.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_name
     *
     * @return the value of sys_authority.auth_name
     *
     * @mbg.generated
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_name
     *
     * @param authName the value for sys_authority.auth_name
     *
     * @mbg.generated
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_desc
     *
     * @return the value of sys_authority.auth_desc
     *
     * @mbg.generated
     */
    public String getAuthDesc() {
        return authDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_desc
     *
     * @param authDesc the value for sys_authority.auth_desc
     *
     * @mbg.generated
     */
    public void setAuthDesc(String authDesc) {
        this.authDesc = authDesc == null ? null : authDesc.trim();
    }
}