package com.xuan.user.facadeimpl.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Role {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.r_name
     *
     * @mbg.generated
     */
    private String rName;

    /**
     * Database Column Remarks:
     *   角色备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.r_remark
     *
     * @mbg.generated
     */
    private String rRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.r_name
     *
     * @return the value of sys_role.r_name
     *
     * @mbg.generated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.r_name
     *
     * @param rName the value for sys_role.r_name
     *
     * @mbg.generated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.r_remark
     *
     * @return the value of sys_role.r_remark
     *
     * @mbg.generated
     */
    public String getrRemark() {
        return rRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.r_remark
     *
     * @param rRemark the value for sys_role.r_remark
     *
     * @mbg.generated
     */
    public void setrRemark(String rRemark) {
        this.rRemark = rRemark == null ? null : rRemark.trim();
    }
}