spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: order-web
  datasource:
#    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: root
    url: jdbc:mysql://192.168.13.170:3306/saas_platform?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Root!@#
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 50
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: Order_HikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 12
    timeout: 10000
    host: 192.168.13.171
    port: 6379
    password: iampassword
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 20
#  redis:
#    database: 0
#    timeout: 10000
#    host: 192.168.13.171
#    port: 6379
#    password: iampassword
#    # 使用 lettuce 连接池需要引入 commons-pools2 包 group: 'org.apache.commons', name: 'commons-pool2', version: '2.6.0'
#    lettuce:
#      pool:
#        max-active: 1000
#        max-idle: 100
#        min-idle: 20
#  data:
#    mongodb:
#      database: log
#      host: 192.168.13.171
#      port: 27017
eureka:
  client:
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    #心跳间隔时间,默认是30秒
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
    lease-expiration-duration-in-seconds: 15

# feign 请求的日志
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  # 开启熔断
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 暴露心跳相关端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true                #开启shutdown 关闭
#rocketmq:
#  namesrvAddr: 192.168.16.175:9876


snowFlake:
  server:
    datacenterId:
    machineId: